import './js/fetchFilms';
import './js/partials/modal-auth';
import './js/auth';
import './js/renderTrends';
import './js/buildTrends';
import './js/renderLocalStorage';
import './js/modal-movie-card';
import './js/switch-day-night';
import './js/arrow_top';
