import './js/fetchFilms';
import './js/renderTrends';
import './js/buildTrends';
import './js/renderLocalStorage';
import './js/modal-movie-card';
import './js/switch-day-night';
import './js/arrow_top';
import './js/local-storage';
import './js/loader';
import './js/noElementsPlug';
import './js/key-url';
import './js/buildSearchedMovies'
import './js/fetchSearchMovies'
