import './js/fetchFilms';
import './js/fetchSearchMovies'
import './js/partials/modal-auth';
import './js/partials/mobile-auth';
import './js/auth';
import './js/renderTrends';
import './js/buildTrends';
import './js/switch-day-night';
import './js/arrow_top';
import './js/local-storage';
import './js/loader';
import './js/noElementsPlug';
import './js/key-url';
import './js/modal-movie-card-close';
import './js/modal-movie-card';
import './js/modal-movie-card-open';
import './js/modal-team'; 
